-- Warehouse Audit System - Supabase starter schema
create table if not exists plants (
  id bigint generated by default as identity primary key,
  plant_code text not null unique,
  plant_name text not null,
  created_at timestamptz default now()
);

create table if not exists warehouses (
  id bigint generated by default as identity primary key,
  plant_code text not null references plants(plant_code),
  warehouse_code text not null unique,
  warehouse_name text not null,
  warehouse_type text not null check (warehouse_type in ('finished','raw')),
  created_at timestamptz default now()
);

create table if not exists movement_definitions (
  id bigint generated by default as identity primary key,
  movement_code text not null,
  sap_description text not null,
  audit_category text not null,
  movement_definition text not null,
  stock_effect text not null check (stock_effect in ('in','out'))
);

create table if not exists audit_uploads (
  id bigint generated by default as identity primary key,
  upload_type text not null check (upload_type in ('sales_transfer','inbound_mb51')),
  report_date date not null,
  file_name text not null,
  uploaded_by text,
  created_at timestamptz default now()
);

create table if not exists audit_transactions (
  id bigint generated by default as identity primary key,
  upload_id bigint references audit_uploads(id) on delete cascade,
  plant_code text,
  warehouse_code text,
  material_code text,
  material_description text,
  unit text,
  quantity numeric default 0,
  quantity_to numeric default 0,
  movement_code text,
  movement_description text,
  posting_date date,
  created_at timestamptz default now()
);

alter table plants enable row level security;
alter table warehouses enable row level security;
alter table movement_definitions enable row level security;
alter table audit_uploads enable row level security;
alter table audit_transactions enable row level security;

-- Development read policy. Tighten before production auth.
create policy if not exists "public read plants" on plants for select using (true);
create policy if not exists "public read warehouses" on warehouses for select using (true);
create policy if not exists "public read movement defs" on movement_definitions for select using (true);
